name: ffh
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  cloud_firestore: ^5.0.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  firebase_auth: ^5.0.0
  cupertino_icons: ^1.0.8
  multi_select_flutter: ^4.1.0
  firebase_storage: ^12.1.0
  google_fonts: ^6.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
  -  assets/homedate1.jpg
  -  assets/homedate2.jpg
  -  assets/homedate3.jpg
  -  assets/homedate1_1.jpg
  -  assets/homedate2_2.jpg
  -  assets/homedate3_1.jpg
  -  assets/homedate4.jpg
  -  assets/homedate4_1.jpg
  -  assets/homedate5.jpg
  -  assets/homedate5_1.jpg
  -  assets/homedate6.jpg
  -  assets/homedate6_1.jpg
  -  assets/homedate7.jpg
  -  assets/homedate7_1.jpg
  -  assets/homedate8.jpg
  -  assets/homedate8_1.jpg
  -  assets/homedate9.jpg
  -  assets/homedate9_1.jpg
  -  assets/homedate10.jpg
  -  assets/homedate10_1.jpg

  









