name: ffh
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  cloud_firestore: ^5.0.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  firebase_auth: ^5.0.0
  cupertino_icons: ^1.0.8
  multi_select_flutter: ^4.1.0
  firebase_storage: ^12.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
  -  assets/home1.jpg
  -  assets/home2.jpg
  -  assets/home3.jpg
  -  assets/home1_1.jpg
  -  assets/home1_2.jpg
  -  assets/home2_1.jpg
  -  assets/home3_1.jpg

  









