name: owner_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  cloud_firestore: ^5.0.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  firebase_auth: ^5.0.0
  multi_select_flutter: ^4.1.0
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0


flutter:



  uses-material-design: true


