name: owner_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  url_launcher: ^6.3.1
  intl: ^0.20.2
  firebase_auth: ^5.6.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  


  flutter_lints: ^5.0.0


flutter:



  uses-material-design: true


