// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4auJ6uuagDSEmx4tNNvqC-EntcSsyIc',
    appId: '1:126192657081:web:1b69d6d098cd98a852b168',
    messagingSenderId: '126192657081',
    projectId: 'ffh-firebase',
    authDomain: 'ffh-firebase.firebaseapp.com',
    storageBucket: 'ffh-firebase.firebasestorage.app',
    measurementId: 'G-LVYVGMM0XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpI7H5yDX_Oahg9fMJQ3F79KqMez7Pq6M',
    appId: '1:126192657081:android:6d601cbac38ac54052b168',
    messagingSenderId: '126192657081',
    projectId: 'ffh-firebase',
    storageBucket: 'ffh-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJQafPpeQfuVNXhticiL12NgmumVGyjM',
    appId: '1:126192657081:ios:2a35083f608a928952b168',
    messagingSenderId: '126192657081',
    projectId: 'ffh-firebase',
    storageBucket: 'ffh-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ffhSdj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJQafPpeQfuVNXhticiL12NgmumVGyjM',
    appId: '1:126192657081:ios:2a35083f608a928952b168',
    messagingSenderId: '126192657081',
    projectId: 'ffh-firebase',
    storageBucket: 'ffh-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ffhSdj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU4auJ6uuagDSEmx4tNNvqC-EntcSsyIc',
    appId: '1:126192657081:web:1f679a63b947483752b168',
    messagingSenderId: '126192657081',
    projectId: 'ffh-firebase',
    authDomain: 'ffh-firebase.firebaseapp.com',
    storageBucket: 'ffh-firebase.firebasestorage.app',
    measurementId: 'G-9L9KNS46BV',
  );

}